
class TestError(Exception):
    pass

class BadNewsBears(TestError):
    pass
